import Footer from "components/Footer";
import Header from "components/Header";
import Heading from "components/Heading";
import Paragraph from "components/Paragraph";
import Wrapper from "components/Wrapper";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Heading>Hello, world!</Heading>
        <Paragraph>
          My name is Grzegorz Pawlik. I am Front-End developer, that praesent
          sed iaculis ante. Fusce ac viverra orci, quis pulvinar urna. Donec sit
          amet est luctus, feugiat turpis ut, ultricies ipsum. Quisque eu magna
          nec.
        </Paragraph>
        <a className="cursor-pointer underline">
          <Paragraph>Download Resume</Paragraph>
        </a>
      </Wrapper>
    </>
  );
}
