import Heading from "components/Heading";
import Paragraph from "components/Paragraph";
import Wrapper from "components/Wrapper";
import Head from "next/head";
import * as contentful from "contentful";

interface Content {
  title: string;
  description: string;
}

export default function Home({ title, description }: Content) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Heading>{title}</Heading>
        <Paragraph>{description}</Paragraph>
        <a className="cursor-pointer underline">
          <Paragraph>Download Resume</Paragraph>
        </a>
      </Wrapper>
    </>
  );
}

export async function getServerSideProps() {
  const client = contentful.createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_CONTENT_DELIVERY_TOKEN,
  });

  const { fields } = await client.getEntry<Content>("OqYxf1dgz4uLLGRVrrvpI");

  return {
    props: {
      title: fields.title,
      description: fields.description,
    },
  };
}
