import Footer from "components/Footer";
import Header from "components/Header";
import Wrapper from "components/Wrapper";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>Hello, world!</Header>
      <Wrapper>
        <div className="grid gap-5">
          <p>
            My name is Grzegorz Pawlik. I am Front-End developer, that praesent
            sed iaculis ante. Fusce ac viverra orci, quis pulvinar urna. Donec
            sit amet est luctus, feugiat turpis ut, ultricies ipsum. Quisque eu
            magna nec.
          </p>
          <a className="underline">Download CV</a>
        </div>
      </Wrapper>
      <Footer />
    </>
  );
}
